dist: trusty
language: c

branches:
  only:
  - master

before_install:
- git clone -b devel --depth 1 git://github.com/nim-lang/Nim.git
- cd Nim
- sh build_all.sh
- export PATH=$PWD/bin:$PATH
- cd ..
install:
- nimble install
script: nimble test